<! DOCTYPE html>
<?php

include_once "./controller/DbController.php";
include_once "./controller/TriggerController.php";
include_once "./controller/IndexController.php";
include_once "./controller/HistoryController.php";
include_once './controller/MainController.php';

$pub_db = new DbController;
$trigger = new TriggerController;
$history = New HistoryController;


 ?>
<header>
	<title>HistoryBook</title>
<link rel="stylesheet" href="style/style.css">

</header>


<body>

    <?if (count ($_GET) > 0):?>
        <div class="title">История изменений</div>
        <!-- Добавление новости -->
        <div class="paragraph">
            <p><strong> <?=$trigger->SetNewNews()['date_create']?></strong>: Добавлена новая новость №<?=$trigger->SetNewNews()['id_new']?> «<?=$trigger->SetNewNews()['title_new']?>»:</p>
        </div>
            <div class="ulist">
                <ul>
                    <li>
                        <p>Название новости: <strong><?=$trigger->SetNewNews()['title_new']?></strong></p>
                    </li>
                    <li>
                        <p>Содержание новости: <strong><?=$trigger->SetNewNews()['content_new']?></strong></p>
                    </li>
                </ul>
            </div>
        <hr>
        <div class="content">

            <? foreach ($history->SetHistory() as $colum_name) :?>
                <!-- ОСТОРОЖНО, КОСТЫЛИ!-->
                <?php
                    // Проверка для соотвестия отображеня содержанимого нужной записи
                    if($colum_name['name_column'] != 'Имя'){
                        $new_value = DbController::SelectNewsById()['content'];
                    } elseif ($colum_name['name_column'] != 'Контент'){
                        $new_value = DbController::SelectNewsById()['title'];
                    }

                    // Проверка на отображение удаленной или актуальной записи
                    if ($trigger->SetDelNews()['id_del'] != null){

                        $value = $trigger->SetDelNews()['title_del'];
                    } else {
                        $value = DbController::SelectNewsById()['title'];
                    }

                ?>
                <!-- ОСТОРОЖНО, КОСТЫЛИ!-->
            <!-- Изменение новости -->
            <div class="paragraph">
                <hr>

                <p><strong><?=$colum_name['date_update']?></strong>: Изменения новости №<?=$colum_name['id_back']?> «<?=$value?>»:</p>
            </div>
            <div class="ulist">
                <ul>
                    <li>
                        <p>Изменено поле «<strong>«<?=$colum_name['name_column']?>»</strong>». Старое значение «<strong><?=$colum_name['content_column']?></strong>». Новое значение «<strong><?=$value?></strong>»</p>
                    </li>
                </ul>
            </div>
                <hr>
            <?endforeach?>
        </div>
        <!-- Удаление новости -->
        <? if($trigger->SetDelNews()['id_del'] != null):?>
            <div class="paragraph">
                <p><strong><?=$trigger->SetDelNews()['date_del']?></strong>: Новость №<?=$trigger->SetDelNews()['id_del']?> «<?=$trigger->SetDelNews()['title_del']?>» была избавлена от этой бренной ноши</p>
            </div>
        <?php endif;?>
    <?php endif;?>


</body>
